### PR TITLE
replaced SMIL animation with CSS animation

### PR DESCRIPTION
**Pull request by sinky**
not "the same" animation, because CSS can't animate the radius but looks the same.

### CODE REVIEW

**Comment by sinky** [comment]
solves #14

**Comment by Tenkir** [comment]
Only solves #14 for one. All need to be updated. But this looks good.

**Comment by SiamKreative** [comment]
Looks great. I'd keep the same indentation though.

**Comment by SamHerbert** [comment]
Thanks @sinky, I'm working on converting these all to CSS.

**Pull request merged**
